ASPHALT_1 = 'resources/Highways/Textures/asphalt_1.png'
DIRT_1 = 'resources/Highways/Textures/dirt_1.png'
SNOW_1 = 'resources/Highways/Textures/snow_1.png'
asph = 'resources/Highways/Textures/asphalt-1.jpg'
road1 = 'resources/Highways/Textures/road1.png'
