BUS_1 = 'resources/Vehicles/Textures/bus_1.png'
BUS_2 = 'resources/Vehicles/Textures/bus_2.png'
BUS_3 = 'resources/Vehicles/Textures/bus_3.png'
BUS_4 = 'resources/Vehicles/Textures/bus_4.png'
BUS_5 = 'resources/Vehicles/Textures/bus_5.png'
